$(document).ready(function(){
    $(".slider1").owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    dots:true,
    navText:[],
    responsive:{
        0:{
            items:1,
            loop:true,
            dots:true,
            nav:false
        },
        870:{
            items:1,
            loop:true,
            dots:false,
            nav:true 
        }
    }
});
});
